language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "4.0"

script:
- npm run lint
- npm test

cache:
  directories:
    - node_moduless

notifications:
  email:
    - christianosholland@gmail.com
